package scaffold

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// GenerateYAML generates a draft lifecycle YAML from resource groups.
func GenerateYAML(groups []ResourceGroup, sourcePath string, timestamp time.Time) string {
	var b strings.Builder

	// Write header
	writeHeader(&b, sourcePath, timestamp)

	// Write lifecycles
	b.WriteString("lifecycles:\n")

	for i, group := range groups {
		if i > 0 {
			b.WriteString("\n")
		}
		writeResourceGroup(&b, group)
	}

	return b.String()
}

// writeHeader writes the prominent draft warning header.
func writeHeader(b *strings.Builder, sourcePath string, timestamp time.Time) {
	b.WriteString(`# ============================================================================
# DRAFT LIFECYCLE SPEC - GENERATED BY ROUTECHECK
# ============================================================================
#
# This file was auto-generated and REQUIRES HUMAN REVIEW before use.
#
# TODO checklist:
#   [ ] Fill in request body fields (replace "TODO" values)
#   [ ] Verify capture JSONPath expressions match your API responses
#   [ ] Confirm expected status codes are correct
#   [ ] Add authentication (not auto-detected)
#   [ ] Test with:
#       routecheck validate --enable-lifecycle --ack-mutations \
#         --lifecycle-file <this-file> <base-url>
#
`)
	fmt.Fprintf(b, "# Generated from: %s\n", sourcePath)
	fmt.Fprintf(b, "# Generated at:   %s\n", timestamp.Format(time.RFC3339))
	b.WriteString(`#
# WARNING: Do not run lifecycle tests without reviewing this file.
#          Lifecycle testing creates REAL resources on your system.
# ============================================================================

`)
}

// writeResourceGroup writes a single resource group as a lifecycle.
func writeResourceGroup(b *strings.Builder, group ResourceGroup) {
	// Resource section comment
	fmt.Fprintf(b, "  # -------------------------------------------------------------------------\n")
	fmt.Fprintf(b, "  # Resource: %s\n", group.Name)
	fmt.Fprintf(b, "  # -------------------------------------------------------------------------\n")

	// Write warnings if any
	for _, warning := range group.Warnings {
		fmt.Fprintf(b, "  # WARNING: %s\n", warning)
	}

	// Lifecycle name
	fmt.Fprintf(b, "  - name: %s-crud\n", group.Name)
	fmt.Fprintf(b, "    description: \"TODO: Describe the %s lifecycle test\"\n", group.Name)
	b.WriteString("\n")

	// CREATE step
	writeCreateStep(b, group)

	// READ step (optional)
	writeReadStep(b, group)

	// CLEANUP step
	writeCleanupStep(b, group)
}

// writeCreateStep writes the CREATE step.
func writeCreateStep(b *strings.Builder, group ResourceGroup) {
	ep := group.CreateEndpoint
	if ep == nil {
		return
	}

	b.WriteString("    create:\n")
	fmt.Fprintf(b, "      method: %s\n", ep.Method)
	fmt.Fprintf(b, "      path: %s\n", ep.Path)

	// Body with TODO placeholders
	b.WriteString("      body:\n")
	if len(ep.BodyFields) > 0 {
		b.WriteString("        # TODO: Fill required fields from your API schema\n")
		b.WriteString("        # Detected schema fields:\n")

		// Sort fields: required first, then alphabetical
		sortedFields := sortBodyFields(ep.BodyFields)
		for _, field := range sortedFields {
			reqStr := ""
			if field.Required {
				reqStr = ", required"
			}
			fmt.Fprintf(b, "        #   - %s (%s%s)\n", field.Name, field.Type, reqStr)
		}

		// Write placeholder values for required fields
		for _, field := range sortedFields {
			if field.Required {
				fmt.Fprintf(b, "        %s: \"TODO\"\n", field.Name)
			}
		}

		// If no required fields, add a generic TODO
		hasRequired := false
		for _, field := range sortedFields {
			if field.Required {
				hasRequired = true
				break
			}
		}
		if !hasRequired {
			b.WriteString("        # TODO: Add required fields\n")
			b.WriteString("        example_field: \"TODO\"\n")
		}
	} else {
		b.WriteString("        # TODO: Fill required fields (no schema detected)\n")
		b.WriteString("        # example_field: \"TODO\"\n")
	}

	// Expected status
	expectedStatus := determineCreateStatus(ep.StatusCodes)
	fmt.Fprintf(b, "      expected_status: [%s]\n", formatStatusCodes(expectedStatus))

	// Capture
	captureVar := determineCaptureVar(group.Name, ep.IDParam)
	b.WriteString("      capture:\n")
	b.WriteString("        # TODO: Verify this JSONPath matches your API response\n")
	fmt.Fprintf(b, "        %s: \"$.id\"\n", captureVar)
	b.WriteString("\n")
}

// writeReadStep writes the READ step (optional).
func writeReadStep(b *strings.Builder, group ResourceGroup) {
	ep := group.ReadEndpoint
	captureVar := determineCaptureVar(group.Name, "")

	if ep == nil {
		// Comment out the read step
		b.WriteString("    # NOTE: No GET /{id} endpoint detected for this resource\n")
		b.WriteString("    # read:\n")
		fmt.Fprintf(b, "    #   method: GET\n")
		fmt.Fprintf(b, "    #   path: %s/{{%s}}\n", group.BasePath, captureVar)
		b.WriteString("    #   expected_status: [200]\n")
		b.WriteString("\n")
		return
	}

	// Get capture var from create endpoint if available
	if group.CreateEndpoint != nil && group.CreateEndpoint.IDParam != "" {
		captureVar = determineCaptureVar(group.Name, group.CreateEndpoint.IDParam)
	}

	b.WriteString("    read:\n")
	fmt.Fprintf(b, "      method: %s\n", ep.Method)

	// Replace ID param with interpolation
	readPath := replaceIDParam(ep.Path, ep.IDParam, captureVar)
	fmt.Fprintf(b, "      path: %s\n", readPath)

	expectedStatus := determineReadStatus(ep.StatusCodes)
	fmt.Fprintf(b, "      expected_status: [%s]\n", formatStatusCodes(expectedStatus))
	b.WriteString("\n")
}

// writeCleanupStep writes the CLEANUP step.
func writeCleanupStep(b *strings.Builder, group ResourceGroup) {
	ep := group.DeleteEndpoint
	captureVar := determineCaptureVar(group.Name, "")

	// Get capture var from create endpoint if available
	if group.CreateEndpoint != nil && group.CreateEndpoint.IDParam != "" {
		captureVar = determineCaptureVar(group.Name, group.CreateEndpoint.IDParam)
	}

	b.WriteString("    cleanup:\n")

	if ep == nil {
		// Generate placeholder cleanup
		b.WriteString("      # TODO: No DELETE endpoint detected. Add manual cleanup:\n")
		b.WriteString("      method: DELETE\n")
		fmt.Fprintf(b, "      path: %s/{{%s}}  # TODO: Verify this path exists\n", group.BasePath, captureVar)
		b.WriteString("      # 404 included: resource may already be deleted or never created\n")
		b.WriteString("      expected_status: [200, 204, 404]\n")
		return
	}

	fmt.Fprintf(b, "      method: %s\n", ep.Method)

	// Replace ID param with interpolation
	cleanupPath := replaceIDParam(ep.Path, ep.IDParam, captureVar)
	fmt.Fprintf(b, "      path: %s\n", cleanupPath)

	b.WriteString("      # 404 included: resource may already be deleted or never created\n")
	expectedStatus := determineCleanupStatus(ep.StatusCodes)
	fmt.Fprintf(b, "      expected_status: [%s]\n", formatStatusCodes(expectedStatus))
}

// sortBodyFields sorts fields with required first, then alphabetically.
func sortBodyFields(fields []BodyField) []BodyField {
	sorted := make([]BodyField, len(fields))
	copy(sorted, fields)

	sort.Slice(sorted, func(i, j int) bool {
		// Required fields first
		if sorted[i].Required != sorted[j].Required {
			return sorted[i].Required
		}
		// Then alphabetically
		return sorted[i].Name < sorted[j].Name
	})

	return sorted
}

// determineCaptureVar determines the capture variable name.
func determineCaptureVar(resourceName, idParam string) string {
	// Use ID param name if available and descriptive
	if idParam != "" {
		lower := strings.ToLower(idParam)
		// Convert camelCase to snake_case
		if strings.Contains(idParam, "Id") {
			return strings.ReplaceAll(strings.ToLower(idParam), "id", "_id")
		}
		if lower != "id" {
			return lower
		}
	}

	// Generate from resource name
	// users → user_id, products → product_id
	singular := singularize(resourceName)
	return singular + "_id"
}

// singularize attempts to singularize a word (simple heuristic).
func singularize(word string) string {
	if strings.HasSuffix(word, "ies") {
		return word[:len(word)-3] + "y"
	}
	if strings.HasSuffix(word, "es") {
		return word[:len(word)-2]
	}
	if strings.HasSuffix(word, "s") && len(word) > 1 {
		return word[:len(word)-1]
	}
	return word
}

// replaceIDParam replaces the ID parameter in a path with an interpolation variable.
func replaceIDParam(path, idParam, captureVar string) string {
	if idParam == "" {
		return path
	}
	placeholder := "{" + idParam + "}"
	interpolation := "{{" + captureVar + "}}"
	return strings.Replace(path, placeholder, interpolation, 1)
}

// determineCreateStatus determines expected status codes for CREATE.
func determineCreateStatus(detected []int) []int {
	// Prefer 201, fall back to 200
	for _, code := range detected {
		if code == 201 {
			return []int{201}
		}
	}
	for _, code := range detected {
		if code == 200 {
			return []int{200}
		}
	}
	return []int{201}
}

// determineReadStatus determines expected status codes for READ.
func determineReadStatus(detected []int) []int {
	for _, code := range detected {
		if code == 200 {
			return []int{200}
		}
	}
	return []int{200}
}

// determineCleanupStatus determines expected status codes for CLEANUP.
func determineCleanupStatus(detected []int) []int {
	// Always include 404 for cleanup (resource may not exist)
	result := []int{}

	has200 := false
	has204 := false
	for _, code := range detected {
		if code == 200 {
			has200 = true
		}
		if code == 204 {
			has204 = true
		}
	}

	if has200 {
		result = append(result, 200)
	}
	if has204 {
		result = append(result, 204)
	}
	if !has200 && !has204 {
		result = append(result, 200, 204)
	}

	result = append(result, 404)
	return result
}

// formatStatusCodes formats status codes as a YAML array string.
func formatStatusCodes(codes []int) string {
	parts := make([]string, len(codes))
	for i, code := range codes {
		parts[i] = fmt.Sprintf("%d", code)
	}
	return strings.Join(parts, ", ")
}
